
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HYPERLINK = 3;
  public static final int CLOSEBAR = 11;
  public static final int EOF = 0;
  public static final int STRING = 2;
  public static final int REFERENCE = 5;
  public static final int IGUAL = 10;
  public static final int error = 1;
  public static final int FECHATAG = 9;
  public static final int CLOSEHYPER = 4;
  public static final int ABRETAG = 8;
  public static final int ASPAS = 12;
  public static final int IMAGE = 6;
  public static final int SOURCE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "HYPERLINK",
  "CLOSEHYPER",
  "REFERENCE",
  "IMAGE",
  "SOURCE",
  "ABRETAG",
  "FECHATAG",
  "IGUAL",
  "CLOSEBAR",
  "ASPAS"
  };
}

