
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 4;
  public static final int PTVIRG = 10;
  public static final int INCREMENT = 9;
  public static final int INTEIRO = 2;
  public static final int MAIOR = 6;
  public static final int COLCHESQ = 13;
  public static final int MENOR = 7;
  public static final int COLCHDIR = 14;
  public static final int EOF = 0;
  public static final int PARENTESQ = 11;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final int PARENTDIR = 12;
  public static final int DO = 3;
  public static final int OUT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEIRO",
  "DO",
  "NUM",
  "OUT",
  "MAIOR",
  "MENOR",
  "IGUAL",
  "INCREMENT",
  "PTVIRG",
  "PARENTESQ",
  "PARENTDIR",
  "COLCHESQ",
  "COLCHDIR"
  };
}

