
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 9;
  public static final int POTENCIA = 8;
  public static final int INTEIRO = 2;
  public static final int MENOS = 4;
  public static final int RESTO = 7;
  public static final int EOF = 0;
  public static final int MULTIPLICA = 5;
  public static final int error = 1;
  public static final int DIVISAO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEIRO",
  "MAIS",
  "MENOS",
  "MULTIPLICA",
  "DIVISAO",
  "RESTO",
  "POTENCIA",
  "PTVIRG"
  };
}

